### ISSUE TITLE
Bug isn't listed when it has open tasks and the devel one is 'invalid'

### ISSUE THREAD

**Issue by panlinux** [canonical/ubuntu-server-triage#17]
From Josh during the #ubunturally:

1. Create a bug with two targeted series: devel and an LTS
2. Mark the bug "fix released" in the devel task
3. Mark the bug "new" in the LTS task
4. Run ustriage to determine if the bug shows up in list

The result is that the bug does, in fact, show up since we do not specifically filter out on status. In this case, it showed up as "Fix released" in the listing.

However, I then marked the devel task as "invalid" leaving the LTS task as "new". The bug no longer showed up in the list of bugs to triage and this is a problem as we should still show this bug in the list.

**Comment by basak** [comment]
I think this just got fixed by #21.

**Comment by basak** [comment]
Though, oddly:

> The result is that the bug does, in fact, show up since we do not specifically filter out on status. In this case, it showed up as "Fix released" in the listing.

That wasn't what I saw before I fixed that. In my case, it didn't show up in that case.

Perhaps this needs some checking before closing.

**Comment by basak** [comment]
Oh, perhaps by "create a bug with two targeted series: devel and an LTS" you mean a special series task for the development series, rather than using the distribution task to represent the development release? Then I can understand how you saw that behaviour, and I think #21 should have fixed it. Probably still work checking though.

**Comment by cpaelzer** [comment]
I tested it today while looking at publishing the new version.
- Bug with Ubuntu+Jammy task => reported
- Bug with Ubuntu (Status tracked in Mantic) + Mantic + jammy task => reported

I think we can call this one resolved.
